export const ADMIN_LANGUAGES = 'ADMIN_LANGUAGES'
export const ADMIN_LANGUAGES_SUCCESS = 'ADMIN_LANGUAGES_SUCCESS'
export const ADMIN_LANGUAGES_FAILURE = 'ADMIN_LANGUAGES_FAILURE'

export const ADMIN_LOGGED_USER = 'ADMIN_LOGGED_USER'
export const ADMIN_LOGGED_USER_SUCCESS = 'ADMIN_LOGGED_USER_SUCCESS'
export const ADMIN_LOGGED_USER_FAILURE = 'ADMIN_LOGGED_USER_FAILURE'
